application: go-play
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /(|compile)
  script: _go_app
